vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO KaHIP/KaMinPar
    REF 00fa1ef4150b558a1260918fe8dc49dae048ea62
    SHA512 4ace64e9d4d55f6d619aa82d819d2299b7e87ceec62f7c8c25b409c07f91c31f0e282149a0fb1369112b6be59c72c2ef11afa8e374e4e70dee00aa302dedcbce
    HEAD_REF main
)

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        -DKAMINPAR_BUILD_APPS=OFF
        -DKAMINPAR_BUILD_IO=OFF
        -DKAMINPAR_BUILD_WITH_SPARSEHASH=OFF
        -DKAMINPAR_BUILD_WITH_DEBUG_SYMBOLS=OFF
        -DKAMINPAR_64BIT_WEIGHTS=ON
        -DKAMINPAR_ENABLE_TIMERS=OFF
        -DKAMINPAR_DOWNLOAD_TBB=OFF
        -DKAMINPAR_BUILD_WITH_KASSERT=OFF
        -DKAMINPAR_BUILD_WITH_MTUNE_NATIVE=OFF
        -DBUILD_TESTING=OFF
        -DCMAKE_POSITION_INDEPENDENT_CODE=ON
)

vcpkg_cmake_install()
vcpkg_cmake_config_fixup(PACKAGE_NAME KaMinPar CONFIG_PATH lib/cmake/KaMinPar)

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include" "${CURRENT_PACKAGES_DIR}/debug/share")

file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
